### ISSUE TITLE
Add a threshold on stars

### ISSUE THREAD

**Issue by Mottie** [musically-ut/lovely-forks#14] opened 2016-02-24 22:45 UTC
I think the threshold for showing a fork should be more than one star.

I forked [this repo](https://github.com/component/textarea-caret-position) to submit a PR, and for fun I starred my own repo... now I have a flamey fork! :grin: 

![2016-02-24 16_44_36-component_textarea-caret-position_ xy coordinates of a textarea or input s caret](https://cloud.githubusercontent.com/assets/136959/13303612/f2b53180-db15-11e5-871e-67e22c9e1423.png)

**Comment by musically-ut** [comment] 2016-02-24 22:47
Nice theme.

However, this is a duplicate of #11. :)

**Closed by musically-ut** 2016-02-24 22:47 UTC

**Comment by Mottie** [comment] 2016-02-24 22:48
Oops! Sorry!

On a note related to issue #13, because of my PR, that repo is now at the top of the organization list, so the "updated_at" must be based on activity.

**Comment by musically-ut** [comment] 2016-02-25 07:25
The `updated_at` changes every time _anything_ (including internal Github processes) change the "repository object". Ivan said in his answer on SO that it may change even if the internal linguist runs and updates the "primary language" of the repository, the `updated_at` will reflect that as well.

Hence, I would not consider it a reliable indicator of activity on the repository. :(
