### ISSUE TITLE
The added message disappears when you click a link in Github

### ISSUE THREAD

**Issue by FatOrangutan** [musically-ut/lovely-forks#43] opened 2018-07-26 02:14 UTC
Lovely Forks (LF) v3.3.0, Firefox

STR:
1. Right click > open in new tab this link: https://github.com/musically-ut/lovely-forks. LF adds `also forked to mcanthony/lovely-forks ★ 1` message under repo name, as expected
2. Now click the `Issues` link in that tab.

AR: LF's message disappears. Reappears on reloading the page though.

**Comment by musically-ut** [comment] 2018-07-26 14:51
Thank you for reporting this.

I too had noticed it and I know I can fix it by using [`github-injection` module](https://www.npmjs.com/package/github-injection). I will include this enhancement in the next release of the extension.

**Comment by musically-ut** [comment] 2020-03-18 16:17
Is it only me, or has GitHub moved away from `pjax` based navigation? 

The link seems to persist even after page change for me. I'll close the issue if the issue is auto-magically fixed with the GitHub fix for others too. :)

**Comment by FatOrangutan** [comment] 2020-03-18 21:38
STR from the original comment indeed work fine now, but the issue can be reproduced with say:

1) Go to https://github.com/musically-ut/lovely-forks/issues
2) Click `Code`.

**Closed** 2020-12-26 18:36 UTC
Labels: help wanted

**Comment by musically-ut** [comment] 2020-12-27 17:36
@FatOrangutan This should be fixed now. :)
